= Guess What

Prise en main de la POO avec PHP

Niveau : Première ou deuxième année de BTS SIO SLAM

Prérequis : bases de la programmation, PHP 8 ou supérieur installé sur votre machine de dev.

== Thème 

Développer une logique de jeu en PHP en mettant en oeuvre de la conception objet et des tests unitaires.

Jeu en mode console. Un début d'implémentation est proposé (`play-console.php` à lancer dans une console)

TIP:  Ce projet est un bon candidat à une application web avec Laravel, éligible comme activité professionnelle si prise en compte des scores des joueurs dans une base de données.


== Objectif

* Conception et mise au point d'une logique applicative avec PHP Objet et PHPUnit

* Structure de données, recherche d'un élément dans une liste

* Analyse des actions du joueur (fonction du nombre de cartes, aides à la décision)

== Les étapes d'un scénario typique d'usage sont

1. (optionnel pour le joueur) paramétrage du jeu (par exemple choix du jeu de cartes, activation de l'aide à la recherche, ...)
2. Lancement d'une partie (le jeu instancie un jeu de carte et tire une carte "au hasard"), que le joueur doit deviner en un *temps optimal*
3. Le joueur propose une carte
4. Si ce n'est pas la bonne carte, alors si l'aide est activée, le joeur est informé si la carte qu'il a soumise est plus petite ou plus grande que celle à deviner. Retour en 3.  Si c'est la bonne carte alors la partie se termine (passe à l'étape suivante)
5. Le jeu affiche des éléments d'analyse (nombre de fois où le joueur a soumis une carte, sa *qualité stratégique*, ...)
6. Fin de la partie.

== Liens du projet
=== Projet Prof : https://gitlab.com/timotirob/guesswhat
=== Projet Groupe : https://github.com/LucSarrazin/GuessWhat/

== Membre du Trinôme
=== Sterenn G.
=== Jeremie B.
=== Luc S.

== Challenge-1 : Prise en main et tests unitaires (4h à 10h)

== Challenge-2 : Implémentation des TODOs de `CardTest` (~2H)
=== Tests unitaires de CardTest

[, php]
----
<?php

namespace App\Tests\Core;

use App\Core\CardGame;
use PHPUnit\Framework\TestCase;
use App\Core\Card;

class CardTest extends TestCase
{


  public function testName()
  {
    $card = new Card('As', 'Trefle');
    $this->assertEquals('As', $card->getName());

    $card = new Card('2', 'Trefle');
    $this->assertEquals('2', $card->getName());
  }

  public function testColor()
  {
    $card = new Card('As', 'Trefle');
    $this->assertEquals('Trefle', $card->getColor());

    $card = new Card('As', 'Pique');
    $this->assertEquals('Pique', $card->getColor());
  }

  public function testCompareSameCard()
  {
    $card1 = new Card('As', 'Trefle');
    $card2 = new Card('As', 'Trefle');
    $this->assertEquals(0, CardGame::compare($card1,$card2));
  }

  public function testCompareSameNameNoSameColor()
  {
      $card1 = new Card('As', 'Trefle');
      $card2 = new Card('As', 'Coeur');

      $this->assertEquals(1, CardGame::compare($card2,$card1));
      $this->assertEquals(-1, CardGame::compare($card1,$card2));

  }

  public function testCompareNoSameNameSameColor()
  {
      $card1 = new Card('2', 'Coeur');
      $card2 = new Card('Dix', 'Coeur');

      $this->assertEquals(1, CardGame::compare($card2,$card1));
      $this->assertEquals(-1, CardGame::compare($card2,$card1));
  }

  public function testCompareNoSameNameNoSameColor()
  {
      $card1 = new Card('Dix', 'Pique');
      $card2 = new Card('Roi', 'Coeur');

      $this->assertEquals(1, CardGame::compare($card1,$card2));
      $this->assertEquals(-1, CardGame::compare($card2,$card1));
  }

  public function testToString()
  {
      $card = new Card('Dix', 'Trefle');

      $this->assertEquals('Dix de Trefle', $card->__toString());
  }

----

== Challenge-3 : Conception de tests unitaires pour `CardGame`
=== Tests unitaires de CardGame

[, php]
----
<?php

namespace App\Tests\Core;

use App\Core\Card;
use App\Core\CardGame;
use PHPUnit\Framework\TestCase;

class CardGameTest extends TestCase
{

  public function testToString2Cards()
  {
    $cardGame = new CardGame([new Card('As', 'Pique'), new Card('Roi', 'Coeur')]);
    $this->assertEquals('CardGame : 2 carte(s)',$cardGame->__toString());
  }

  public function testToString1Card()
  {
    $cardGame = new CardGame([new Card('As', 'Pique')]);
    $this->assertEquals('CardGame : 1 carte(s)',$cardGame->__toString());
  }

  public function testCompare()
  {
    $card1 = new Card('As', 'Pique');
    $card2 = new Card('As', 'Pique');
    $cardGame = new CardGame([$card1, $card2]);
    $this->assertEquals(0, $cardGame->compare($card1, $card2));
  }

  public function testShuffle()
  {
    $cardGame = new CardGame(CardGame::factory52Cards());
    $cartesMelangees = $cardGame->shuffle($cardGame->getCards());
    $this->assertEquals($cartesMelangees, $cardGame->shuffle($cardGame->getCards()));
  }

  public function testGetCard()
{
    $cardGame = new CardGame(CardGame::factory52Cards());
    $this->assertEquals('Dix de Trefle', $cardGame->getCard(0));
}
  public function testFactoryCardGame32()
{
  $paquet = CardGame::factory32Cards();
  $this->assertEquals(32, count($paquet));
}

}
----

== Challenge-4 : Conception de tests unitaires pour `Game` (~4h à 8h)
=== Tests unitaires Game

[, php]
----
<?php

namespace App\Tests\Core;

use App\Core\CardGame;
use App\Core\Game;
use PHPUnit\Framework\TestCase;

class GameTest extends TestCase
{
  public function testDefaultValues() {
    $jeuDeCartes = new CardGame(CardGame::factory32Cards());
    $game = new Game($jeuDeCartes);
    $this->assertNotNull($game->getCardToGuess());
    $this->assertTrue($game->getWithHelp());
  }

  public function testDefaultValueWithHelp() {
    $jeuDeCartes = new CardGame(CardGame::factory52Cards());
    $guess = new Guess($jeuDeCartes);
    $this->assertNotTrue($guess->getWithHelp());
 }
}
----
