= Guess What

Prise en main de la POO avec PHP

Niveau : Première ou deuxième année de BTS SIO SLAM

Prérequis : bases de la programmation, PHP 8 ou supérieur installé sur votre machine de dev.

== Thème 

Développer une logique de jeu en PHP en mettant en oeuvre de la conception objet et des tests unitaires.

Jeu en mode console. Un début d'implémentation est proposé (`play-console.php` à lancer dans une console)

TIP:  Ce projet est un bon candidat à une application web avec Laravel, éligible comme activité professionnelle si prise en compte des scores des joueurs dans une base de données.


== Objectif

* Conception et mise au point d'une logique applicative avec PHP Objet et PHPUnit

* Structure de données, recherche d'un élément dans une liste

* Analyse des actions du joueur (fonction du nombre de cartes, aides à la décision)

== Les étapes d'un scénario typique d'usage sont

1. (optionnel pour le joueur) paramétrage du jeu (par exemple choix du jeu de cartes, activation de l'aide à la recherche, ...)
2. Lancement d'une partie (le jeu instancie un jeu de carte et tire une carte "au hasard"), que le joueur doit deviner en un *temps optimal*
3. Le joueur propose une carte
4. Si ce n'est pas la bonne carte, alors si l'aide est activée, le joeur est informé si la carte qu'il a soumise est plus petite ou plus grande que celle à deviner. Retour en 3.  Si c'est la bonne carte alors la partie se termine (passe à l'étape suivante)
5. Le jeu affiche des éléments d'analyse (nombre de fois où le joueur a soumis une carte, sa *qualité stratégique*, ...)
6. Fin de la partie.

== Premiers éléments d'analyse

[plantuml]
----
class Game {
  withHelp : boolean

  start()
  isMatch(c : Card) : boolean
  getStatistic() : string
}

class CardGame {
  name
  {static} compare(Card c1, Card c2) : int
}


class Card {
  name
  color
}

Game"*" -> "\ncardToGuess  1  " Card : "                             "
Game"*" -> "cardGame 1  " CardGame : "                                     "
CardGame "*" --> "   * cards  " Card : "                                     "
hide circle
----

Cette analyse est une première ébauche, donc incomplète et à ajuster, mais suffisante pour réaliser vos premiers pas sur ce projet. Qu'est-ce qu'elle nous dit ?

* Une instance de `Game` est liée à une instance de `CardGame` (un jeu de cartes) nommée `cardGame` et à une instance de `Card` nommée `cardToGuess` (la carte à deviner)
* Une instance de `CardGame` est liée à une collection de cartes (`array` of instances of `Card`) nommées `cards`.

Pour l'essentiel (le cours associé apportera d'autres informations et répondra à vos questions) :

* La classe `Game` est responsable de la logique du jeu.
* La classe `CardGame` définit la structure d'un jeu de cartes classique (de type jeu de 32 ou 54 cartes) et ses méthodes.
* La classe `Card` définit la structure d'une carte à jouer et ses méthodes.

En résumé : Une instance de `Game` est reliée, à un instant _t_, à un jeu de cartes, lui-même reliè à un ensemble de cartes  (`cards`), et à une instance de `Card` (`cardToGuess` est la carte que le joueur doit deviner)

== Première implémentation

Classe `Card` (extrait. Localisation : `src/Core/Card.php`)

[, php]
----
<?php
namespace App\Core;

/**
 * Class Card : Définition d'une carte à jouer
 * @package App\Core
 */
class Card
{
  /**
   * @var $name string nom de la carte, comme par exemples 'As' '2' 'Reine'
   */
  private $name;

  /**
   * @var $color string couleur de la carte, par exemples 'Pique', 'Carreau'
   */
  private $color; 

  /**
   * @return string
   */
  public function getName(): string
  {
    return $this->name;
  }

  // [...]
}
----


Classe `Game` (incomplète. Localisation : `src/Core/Game.php`)

[, php]
----
<?php

namespace App\Core;

/**
 * Class Game : la logique du jeu.
 * @package App\Core
 */
class Game
{
  /**
   * @var CardGame un jeu de cartes
   */
  private $cardGame;

  /**
   * @var Card c'est la carte à deviner par le joueur
   */
  private $cardToGuess;

  /**
   * @var bool pour prendre en compte lors d'une partie
   */
  private $withHelp;
}
----

NOTE: L'usage de la syntaxe de documentation PHPDoc https://docs.phpdoc.org/3.0/guide/getting-started/what-is-a-docblock.html[DocBloc] est attendue dans votre code !


== Challenge-1 : Prise en main et tests unitaires (4h à 10h)

== Challenge-2 : Implémentation des TODOs de `CardTest` (~2H)
=== Teste unitaire de CardTest

[, php]
----
<?php

namespace App\Tests\Core;

use App\Core\CardGame;
use PHPUnit\Framework\TestCase;
use App\Core\Card;

class CardTest extends TestCase
{


  public function testName()
  {
    $card = new Card('As', 'Trefle');
    $this->assertEquals('As', $card->getName());

    $card = new Card('2', 'Trefle');
    $this->assertEquals('2', $card->getName());
  }

  public function testColor()
  {
    $card = new Card('As', 'Trefle');
    $this->assertEquals('Trefle', $card->getColor());

    $card = new Card('As', 'Pique');
    $this->assertEquals('Pique', $card->getColor());
  }

  public function testCompareSameCard()
  {
    $card1 = new Card('As', 'Trefle');
    $card2 = new Card('As', 'Trefle');
    $this->assertEquals(0, CardGame::compare($card1,$card2));
  }

  public function testCompareSameNameNoSameColor()
  {
      $card1 = new Card('As', 'Trefle');
      $card2 = new Card('As', 'Coeur');

      $this->assertEquals(1, CardGame::compare($card2,$card1));
      $this->assertEquals(-1, CardGame::compare($card1,$card2));

  }

  public function testCompareNoSameNameSameColor()
  {
      $card1 = new Card('2', 'Coeur');
      $card2 = new Card('Dix', 'Coeur');

      $this->assertEquals(1, CardGame::compare($card2,$card1));
      $this->assertEquals(-1, CardGame::compare($card2,$card1));
  }

  public function testCompareNoSameNameNoSameColor()
  {
      $card1 = new Card('Dix', 'Pique');
      $card2 = new Card('Roi', 'Coeur');

      $this->assertEquals(1, CardGame::compare($card1,$card2));
      $this->assertEquals(-1, CardGame::compare($card2,$card1));
  }

  public function testToString()
  {
      $card = new Card('Dix', 'Trefle');

      $this->assertEquals('Dix de Trefle', $card->__toString());
  }

----

== Challenge-3 : Conception de tests unitaires pour `CardGame`
=== Teste unitaire de CardGame

[, php]
----
<?php

namespace App\Tests\Core;

use App\Core\Card;
use App\Core\CardGame;
use PHPUnit\Framework\TestCase;

class CardGameTest extends TestCase
{

  public function testToString2Cards()
  {
    $cardGame = new CardGame([new Card('As', 'Pique'), new Card('Roi', 'Coeur')]);
    $this->assertEquals('CardGame : 2 carte(s)',$cardGame->__toString());
  }

  public function testToString1Card()
  {
    $cardGame = new CardGame([new Card('As', 'Pique')]);
    $this->assertEquals('CardGame : 1 carte(s)',$cardGame->__toString());
  }

  public function testCompare()
  {
    $card1 = new Card('As', 'Pique');
    $card2 = new Card('As', 'Pique');
    $cardGame = new CardGame([$card1, $card2]);
    $this->assertEquals(0, $cardGame->compare($card1, $card2));
  }

  public function testShuffle()
  {
    $cardGame = new CardGame(CardGame::factory52Cards());
    $cartesMelangees = $cardGame->shuffle($cardGame->getCards());
    $this->assertEquals($cartesMelangees, $cardGame->shuffle($cardGame->getCards()));
  }

  public function testGetCard()
{
    $cardGame = new CardGame(CardGame::factory52Cards());
    $this->assertEquals('Dix de Trefle', $cardGame->getCard(0));
}
  public function testFactoryCardGame32()
{
  $paquet = CardGame::factory32Cards();
  $this->assertEquals(32, count($paquet));
}

}
----

== Challenge-4 : Conception de tests unitaires pour `Game` (~4h à 8h)
=== Testes unitaire Game

[, php]
----
<?php

namespace App\Tests\Core;

use App\Core\CardGame;
use PHPUnit\Framework\TestCase;
use App\Core\Card;

class CardTest extends TestCase
{


  public function testName()
  {
    $card = new Card('As', 'Trefle');
    $this->assertEquals('As', $card->getName());

    $card = new Card('2', 'Trefle');
    $this->assertEquals('2', $card->getName());
  }

  public function testColor()
  {
    $card = new Card('As', 'Trefle');
    $this->assertEquals('Trefle', $card->getColor());

    $card = new Card('As', 'Pique');
    $this->assertEquals('Pique', $card->getColor());
  }

  public function testCompareSameCard()
  {
    $card1 = new Card('As', 'Trefle');
    $card2 = new Card('As', 'Trefle');
    $this->assertEquals(0, CardGame::compare($card1,$card2));
  }

  public function testCompareSameNameNoSameColor()
  {
      $card1 = new Card('As', 'Trefle');
      $card2 = new Card('As', 'Coeur');

      $this->assertEquals(1, CardGame::compare($card2,$card1));
      $this->assertEquals(-1, CardGame::compare($card1,$card2));

  }

  public function testCompareNoSameNameSameColor()
  {
      $card1 = new Card('2', 'Coeur');
      $card2 = new Card('Dix', 'Coeur');

      $this->assertEquals(1, CardGame::compare($card2,$card1));
      $this->assertEquals(-1, CardGame::compare($card2,$card1));
  }

  public function testCompareNoSameNameNoSameColor()
  {
      $card1 = new Card('Dix', 'Pique');
      $card2 = new Card('Roi', 'Coeur');

      $this->assertEquals(1, CardGame::compare($card1,$card2));
      $this->assertEquals(-1, CardGame::compare($card2,$card1));
  }

  public function testToString()
  {
      $card = new Card('Dix', 'Trefle');

      $this->assertEquals('Dix de Trefle', $card->__toString());
  }

----
